# Generated by Django 4.0.4 on 2022-06-27 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCms',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_top', models.CharField(max_length=100)),
                ('text_top', models.TextField()),
                ('slide_first_video', models.CharField(max_length=100)),
                ('slide_first_header', models.TextField()),
                ('slide_first_text', models.TextField()),
                ('slide_second_video', models.CharField(max_length=100)),
                ('slide_second_header', models.TextField()),
                ('slide_second_text', models.TextField()),
                ('slide_third_video', models.CharField(max_length=100)),
                ('slide_third_header', models.TextField()),
                ('slide_third_text', models.TextField()),
                ('middle_header_first', models.CharField(max_length=100)),
                ('middle_text_first', models.TextField()),
                ('middle_video_first', models.TextField()),
                ('middle_header_second', models.CharField(max_length=100)),
                ('middle_text_second', models.TextField()),
                ('middle_video_second', models.TextField()),
                ('middle_header_third', models.CharField(max_length=100)),
                ('middle_text_third', models.TextField()),
                ('middle_video_third', models.TextField()),
                ('middle_header_fourth', models.CharField(max_length=100)),
                ('middle_text_fourth', models.TextField()),
                ('middle_video_fourth', models.TextField()),
                ('middle_header_fifth', models.CharField(max_length=100)),
                ('middle_text_fifth', models.TextField()),
                ('middle_video_fifth', models.TextField()),
                ('bottom_header', models.CharField(max_length=100)),
                ('bottom_text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeCmsClientsSlider',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_image', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
