# Generated by Django 4.0.4 on 2022-06-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecms',
            name='video_top',
            field=models.FileField(blank=True, upload_to='my_stuff'),
        ),
    ]
