# Generated by Django 4.0.4 on 2022-07-02 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('passive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDataTable',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('admin_type', models.IntegerField(default=1)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('token', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='homecms',
            name='middle_video_fifth',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='middle_video_first',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='middle_video_fourth',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='middle_video_second',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='middle_video_third',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='slide_first_video',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='slide_second_video',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='slide_third_video',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='video_top',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecmsclientsslider',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
