# Generated by Django 4.0.4 on 2022-07-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive', '0002_admindatatable_alter_homecms_middle_video_fifth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindatatable',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
