# Generated by Django 4.0.4 on 2022-07-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive', '0003_alter_admindatatable_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecmsclientsslider',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
