# Generated by Django 4.0.4 on 2022-06-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive', '0004_alter_homecms_middle_video_fifth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecms',
            name='middle_video_fifth',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='middle_video_first',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='middle_video_fourth',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='middle_video_second',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='middle_video_third',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='slide_first_video',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='slide_second_video',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='slide_third_video',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
        migrations.AlterField(
            model_name='homecms',
            name='video_top',
            field=models.FileField(blank=True, default='', upload_to='home_cms'),
        ),
    ]
