# Generated by Django 4.0.4 on 2022-06-29 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('passive', '0005_alter_homecms_middle_video_fifth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('admin_type', models.IntegerField(default=1)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_pictures')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
