# Generated by Django 4.0.4 on 2022-07-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive', '0006_changesrequesttable_userleadstable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesrequesttable',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
