# Generated by Django 4.0.4 on 2022-07-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive', '0007_alter_changesrequesttable_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleadstable',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
