# Generated by Django 4.0.4 on 2022-07-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passive', '0008_alter_userleadstable_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='changesrequesttable',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passive.usertable'),
            preserve_default=False,
        ),
    ]
